import * as pdfjsLib from 'pdfjs-dist/build/pdf.mjs';
import { normalizeLines, blocksFromPages } from './textExtraction.mjs';

pdfjsLib.GlobalWorkerOptions.workerSrc = chrome.runtime.getURL('pdf/pdf.worker.mjs');

const DEFAULTS = { typographyEnabled:false, readingAidsEnabled:false, boldBeginning:false, emotionColor:false, emotionMode:'local', gradientRows:false, transitionAnimation:false, sentenceLabels:false, sentenceLabelsLens:'inform', sentenceLabelsDensity:'medium', rulerActive:false, rulerWindowLines:1.5, autoScrollActive:false, autoScrollSpeed:2, typewriterActive:false, typewriterSpeed:5, fontSize:18, lineHeight:1.8, fontFamily:'', wordSpacing:0, letterSpacing:0, rowShadingColor:'#bfb3d0', emotionPositiveColor:'#27ae60', emotionNegativeColor:'#e74c3c', emotionComplexColor:'#8e44ad', labelKeyPointColor:'#eab308', labelCoreDetailColor:'#3b82f6', labelConceptColor:'#9333ea', labelReasoningColor:'#f97316', labelTakeawayColor:'#0d9488', labelClaimColor:'#ca8a04', labelEvidenceColor:'#22c55e', labelCounterpointColor:'#e11d48' };
const FALLBACK_WORDS = { emotionPositive:['joy','hope','love','success','progress','happy','confidence'], emotionNegative:['fear','anger','loss','pain','crisis','danger','failure'], emotionComplex:['uncertain','complex','ambiguous','tension','controversial','skeptical'], transition:['however','therefore','moreover','furthermore','consequently','although','meanwhile','for example','in conclusion','in summary','in contrast','because','thus','indeed'] };
const DENSITY = { low:85, medium:75, high:65 };
let settings = { ...DEFAULTS }, wordLists = { ...FALLBACK_WORDS }, documentModel, ownTabId = null;
let labelBySentence = new Map(), emotionWords = [], focusKeywords = null, focusPrefixes = null, tw = null, typeTimer = null, typeInterval = 38;
let emotionPending = null, labelPending = null, focusRequestId = null, autoFrame, lastFrame;
const app = document.getElementById('app'), article = document.getElementById('article'), scroll = document.getElementById('scroll');

function escapeHTML(s) { return s.replace(/[&<>"']/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;', "'":'&#039;' }[c])); }
function escapeRegex(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }
function splitSentences(text) { return text.split(/(?<=[.!?])\s+(?=[A-Z"'])/).filter(Boolean); }
function allSentences() { return documentModel?.blocks.flatMap(block => splitSentences(block.text)) ?? []; }
function typeSpeed(level) { return 70 - ((Math.min(10, Math.max(1, Number(level) || 5)) - 1) * 60 / 9); }
function bionic(text) { return escapeHTML(text).replace(/\b([A-Za-z]{2,})(?=\b)/g, word => `<b>${word.slice(0, Math.min(4, Math.ceil(word.length / 2)))}</b>${word.slice(Math.min(4, Math.ceil(word.length / 2)))}`); }
function words(category) { return wordLists[category] ?? FALLBACK_WORDS[category] ?? []; }
function wordClass(word) { const lower = word.toLowerCase(); const ai = emotionWords.find(h => h.word?.toLowerCase() === lower); if (ai?.category) return ai.category.replace('emotion-', ''); if (words('emotionPositive').some(w => w.toLowerCase() === lower)) return 'positive'; if (words('emotionNegative').some(w => w.toLowerCase() === lower)) return 'negative'; if (words('emotionComplex').some(w => w.toLowerCase() === lower)) return 'complex'; return ''; }
function focused(text) { if (focusKeywords) { const low = text.toLowerCase(); return focusKeywords.some(k => low.includes(k)); } if (focusPrefixes) { const prefix = text.trim().slice(0, 30); return focusPrefixes.some(p => prefix.startsWith(p.slice(0, 25))); } return true; }
function decorate(text, index) {
  let html = settings.boldBeginning ? bionic(text) : escapeHTML(text);
  if (settings.readingAidsEnabled && settings.transitionAnimation) {
    const regex = new RegExp(`(?<![a-zA-Z-])(${words('transition').map(escapeRegex).join('|')})(?![a-zA-Z-])`, 'gi');
    html = html.replace(regex, '<span class="transition">$1</span>');
  }
  if (settings.readingAidsEnabled && settings.emotionColor) html = html.replace(/\b([A-Za-z]+)\b/g, (match, word) => { const kind = wordClass(word); return kind ? `<span class="${kind}">${match}</span>` : match; });
  const label = labelBySentence.get(index);
  return `<span class="sentence${label ? ` label-${label}` : ''}${focused(text) ? '' : ' reader-muted'}">${html}</span>`;
}
function flatSentences() { const flat=[]; documentModel.blocks.forEach((block, blockIndex) => splitSentences(block.text).forEach((text, i) => flat.push({ text, blockIndex, isBlockStart:i===0 }))); return flat; }
function renderNormal() { let index=0; return documentModel.blocks.map(block => `<p class="block">${splitSentences(block.text).map(s => decorate(s, index++)).join(' ')}</p>`).join(''); }
function renderPickStart() { let html='<div class="dra-tw-banner"><div class="dra-tw-banner-main">Click any sentence to start reading from there, or <button data-tw-action="start-beginning">Start from Beginning</button></div><div class="dra-tw-banner-hint">Press Space to continue, or press Space while typing to reveal the full paragraph.</div></div>'; let open=false; tw.flatSentences.forEach((s,i)=>{ if(s.isBlockStart) { if(open) html+='</p>'; html+='<p class="block">'; open=true; } html+=`<span class="sentence dra-tw-pickable" data-tw-index="${i}">${escapeHTML(s.text)}</span> `; }); return html+(open?'</p>':''); }
function renderTyping() { let html='', open=false; for(let i=0;i<=tw.currentIndex && i<tw.flatSentences.length;i++) { const s=tw.flatSentences[i]; if(s.isBlockStart) { if(open) html+='</p>'; html+='<p class="block">'; open=true; } if(i!==tw.currentIndex) html+=decorate(s.text,i)+' '; else if(tw.phase==='typing') html+=`<span class="sentence dra-tw-current dra-tw-typing">${escapeHTML(s.text.slice(0,tw.revealedChars))}</span> `; else { const label=labelBySentence.get(i), rendered=decorate(s.text,i).replace(/^<span[^>]*>|<\/span>$/g,''); html+=`<span class="sentence dra-tw-current${label?` label-${label}`:''}${focused(s.text)?'':' reader-muted'}">${rendered}</span> `; } } if(open) html+='</p>'; if(tw.phase==='paused'&&tw.showContinueHint) html+='<div class="dra-tw-continue-hint">Space to continue</div>'; return html; }
function render() { if(!documentModel) return; article.innerHTML=`<h1>${escapeHTML(documentModel.title)}</h1>${tw?.phase==='picking-start' ? renderPickStart() : tw ? renderTyping() : renderNormal()}`; applyStyles(); updateProgress(); }
function clearContinueHintTimer() { if(tw?.continueHintTimer) clearTimeout(tw.continueHintTimer); if(tw) tw.continueHintTimer=null; }
function scheduleContinueHint() { clearContinueHintTimer(); if(!tw||tw.currentIndex+1>=tw.flatSentences.length)return; tw.continueHintTimer=setTimeout(()=>{if(tw?.phase==='paused'){tw.showContinueHint=true;render();}},2000); }
function setTypewriter(active) { clearInterval(typeTimer); clearContinueHintTimer(); if(active&&documentModel) { tw={phase:'picking-start',flatSentences:flatSentences(),startIndex:null,currentIndex:-1,revealedChars:0,continueHintTimer:null,showContinueHint:false}; scroll.classList.remove('dra-tw-scroll-pad'); } else { tw=null; scroll.classList.remove('dra-tw-scroll-pad'); } render(); }
function centerCurrent() { const cur=article.querySelector('.dra-tw-current'); if(!cur)return; const containerRect=scroll.getBoundingClientRect(), curRect=cur.getBoundingClientRect(); scroll.scrollTop+=(curRect.top+curRect.height/2)-(containerRect.top+containerRect.height/2); }
function startTyping(index) { clearContinueHintTimer(); clearInterval(typeTimer); tw.currentIndex=index;tw.revealedChars=0;tw.phase='typing';tw.showContinueHint=false;const text=tw.flatSentences[index].text;render();centerCurrent();typeTimer=setInterval(()=>{tw.revealedChars++;if(tw.revealedChars>=text.length){clearInterval(typeTimer);tw.phase='paused';scheduleContinueHint();}render();centerCurrent();},typeInterval); }
function chooseStart(index) { scroll.classList.add('dra-tw-scroll-pad'); tw.startIndex=index; startTyping(index); }
function revealParagraph() { clearContinueHintTimer();clearInterval(typeTimer);const current=tw.flatSentences[tw.currentIndex];while(tw.currentIndex+1<tw.flatSentences.length&&tw.flatSentences[tw.currentIndex+1].blockIndex===current.blockIndex)tw.currentIndex++;tw.revealedChars=tw.flatSentences[tw.currentIndex].text.length;tw.phase='paused';tw.showContinueHint=false;scheduleContinueHint();render();centerCurrent(); }
function advanceTypewriter() { if(!tw)return;if(tw.phase==='picking-start'){chooseStart(0);return;}if(tw.phase==='typing'){revealParagraph();return;}if(tw.phase==='paused'){clearContinueHintTimer();tw.showContinueHint=false;if(tw.currentIndex+1<tw.flatSentences.length)startTyping(tw.currentIndex+1);else{tw.phase='finished';render();}} }
function applyStyles() { app.style.setProperty('--positive',settings.emotionPositiveColor); app.style.setProperty('--negative',settings.emotionNegativeColor); app.style.setProperty('--complex',settings.emotionComplexColor); app.style.setProperty('--row',settings.rowShadingColor); app.style.setProperty('--label-key-point',settings.labelKeyPointColor); app.style.setProperty('--label-core-detail',settings.labelCoreDetailColor); app.style.setProperty('--label-concept',settings.labelConceptColor); app.style.setProperty('--label-reasoning',settings.labelReasoningColor); app.style.setProperty('--label-takeaway',settings.labelTakeawayColor); app.style.setProperty('--label-claim',settings.labelClaimColor); app.style.setProperty('--label-evidence',settings.labelEvidenceColor); app.style.setProperty('--label-counterpoint',settings.labelCounterpointColor); article.style.fontSize=settings.typographyEnabled?`${settings.fontSize||18}px`:''; article.style.lineHeight=settings.typographyEnabled?String(settings.lineHeight||1.8):''; article.style.fontFamily=settings.typographyEnabled&&settings.fontFamily?settings.fontFamily:''; article.style.wordSpacing=settings.typographyEnabled?`${settings.wordSpacing||0}em`:''; article.style.letterSpacing=settings.typographyEnabled?`${settings.letterSpacing||0}em`:''; app.classList.toggle('rows',Boolean(settings.readingAidsEnabled&&settings.gradientRows)); updateRuler(); updateAutoscroll(); }
function updateRuler(e) { const active=settings.readingAidsEnabled&&settings.rulerActive; const y=e?.clientY??innerHeight/2, half=16*1.8*(settings.rulerWindowLines||1.5)/2; document.querySelectorAll('.ruler').forEach(el=>el.classList.toggle('active',active)); document.getElementById('ruler-top').style.height=`${Math.max(0,y-half)}px`; document.getElementById('ruler-bottom').style.height=`${Math.max(0,innerHeight-y-half)}px`; }
function updateAutoscroll() { cancelAnimationFrame(autoFrame); lastFrame=undefined; if(tw||!settings.readingAidsEnabled||!settings.autoScrollActive) return; const speed=15+(((settings.autoScrollSpeed||2)-1)*165/9); const tick=t=>{ if(lastFrame) scroll.scrollTop+=speed*(t-lastFrame)/1000; lastFrame=t; autoFrame=requestAnimationFrame(tick); }; autoFrame=requestAnimationFrame(tick); }
function updateProgress() { let progress; if (tw) { const total=tw.flatSentences.length; progress=tw.phase==='finished' ? 1 : total>0&&tw.currentIndex>=0 ? (tw.currentIndex+1)/total : 0; } else { const max=scroll.scrollHeight-scroll.clientHeight; progress=max<=0?1:scroll.scrollTop/max; } document.querySelector('#progress i').style.width=`${Math.min(1,Math.max(0,progress))*100}%`; }
async function loadSession(id) { return new Promise((resolve,reject)=>{ const r=indexedDB.open('argus-pdf',1); r.onerror=()=>reject(r.error); r.onsuccess=()=>{ const db=r.result, tx=db.transaction('sessions','readwrite'), get=tx.objectStore('sessions').get(id); get.onsuccess=()=>{ const value=get.result; tx.objectStore('sessions').delete(id); value?resolve(value.file):reject(new Error('This PDF session has expired. Please select the file again.')); }; tx.oncomplete=()=>db.close(); }; }); }
async function fingerprint(data) { const digest=await crypto.subtle.digest('SHA-256',data); return [...new Uint8Array(digest)].slice(0,12).map(n=>n.toString(16).padStart(2,'0')).join(''); }
function sendPdf(type, payload = {}) { chrome.runtime.sendMessage({ type, tabId: ownTabId, ...payload }); }
function sendStatus(feature,status) { sendPdf('AI_STATUS', { feature, status }); }
function requestEmotion() { if(!documentModel||emotionPending||settings.emotionMode!=='ai'||!settings.emotionColor||!settings.readingAidsEnabled) return; const chunks=[]; let current=''; documentModel.blocks.forEach(block=>{ if(current&&current.length+block.text.length>55000){chunks.push(current);current='';} current+=`${current?'\n\n':''}${block.text}`; }); if(current) chunks.push(current); const requestId=`pdf:emotion:${Date.now()}`; emotionPending={requestId,remaining:chunks.length,highlights:[]}; sendStatus('emotion','loading'); chunks.forEach((text,chunk)=>sendPdf('PDF_EMOTION_REQUEST',{requestId,chunk,text,fingerprint:documentModel.fingerprint})); }
function requestLabels() { if(!documentModel||labelPending||!settings.sentenceLabels||!settings.readingAidsEnabled) return; const sentences=allSentences(), requestId=`pdf:labels:${Date.now()}`, batchSize=200, batches=[]; for(let start=0;start<sentences.length;start+=batchSize)batches.push({start,sentences:sentences.slice(start,start+batchSize)}); labelPending={requestId,remaining:batches.length,labels:new Map()}; sendStatus('labels','loading'); batches.forEach(batch=>sendPdf('PDF_LABEL_REQUEST',{requestId,batchStart:batch.start,sentences:batch.sentences,fingerprint:documentModel.fingerprint,lensPurpose:settings.sentenceLabelsLens,minImportance:DENSITY[settings.sentenceLabelsDensity]||75})); }
function runAiIfNeeded() { requestEmotion(); requestLabels(); }
function requestFocus(topic) { if(!documentModel)return; focusRequestId=`pdf:focus:${Date.now()}`; sendStatus('focus','loading'); sendPdf('PDF_FOCUS_ANALYZE',{requestId:focusRequestId,topic,text:documentModel.blocks.map(b=>b.text).join('\n\n').slice(0,60000),fingerprint:documentModel.fingerprint}); }
async function loadPdf() { const params=new URLSearchParams(location.search); let data, fallback=params.get('title')||'PDF document'; try { if(params.get('session')) data=await(await loadSession(params.get('session'))).arrayBuffer(); else { const response=await fetch(params.get('url')); if(!response.ok)throw new Error(`Download failed (${response.status})`); data=await response.arrayBuffer(); } const hash=await fingerprint(data), pdf=await pdfjsLib.getDocument({data}).promise, pages=[]; for(let i=1;i<=pdf.numPages;i++){article.innerHTML=`<p class="status">Extracting text… ${i} / ${pdf.numPages}</p>`; const content=await(await pdf.getPage(i)).getTextContent(); pages.push({number:i,lines:normalizeLines(content.items)});} const metadata=await pdf.getMetadata().catch(()=>null), title=metadata?.info?.Title?.trim()||fallback.replace(/\.pdf$/i,''), blocks=blocksFromPages(pages); if(!blocks.length)throw new Error('This PDF has no readable text layer. It may be a scanned PDF and needs OCR.'); documentModel={title,blocks,fingerprint:hash}; render(); chrome.runtime.sendMessage({type:'PDF_READER_STATUS',active:true,tabId:ownTabId}); runAiIfNeeded(); } catch(error){article.innerHTML=`<p class="status error">${escapeHTML(error.message||'Could not open this PDF.')}</p>`;} }
function handlePdfMessage(msg) { if(msg.targetPdfTabId!==ownTabId)return; if(msg.type==='PDF_EMOTION_RESULT'&&emotionPending?.requestId===msg.requestId){emotionPending.highlights.push(...(msg.highlights||[])); if(!--emotionPending.remaining){emotionWords=emotionPending.highlights; emotionPending=null; sendStatus('emotion','success'); render();}} if(msg.type==='PDF_EMOTION_ERROR'&&emotionPending?.requestId===msg.requestId){emotionPending=null;sendStatus('emotion','error');} if(msg.type==='PDF_LABEL_RESULT'&&labelPending?.requestId===msg.requestId){(msg.labels||[]).forEach(l=>labelPending.labels.set(msg.batchStart+l.index,l.type)); if(!--labelPending.remaining){labelBySentence=labelPending.labels;labelPending=null;sendStatus('labels','success');render();}} if(msg.type==='PDF_LABEL_ERROR'&&labelPending?.requestId===msg.requestId){labelPending=null;sendStatus('labels','error');} if(msg.type==='PDF_FOCUS_APPLY'){focusPrefixes=null;focusKeywords=msg.keywords;render();} if(msg.type==='PDF_FOCUS_CLEAR'){focusKeywords=null;focusPrefixes=null;sendStatus('focus',null);render();} if(msg.type==='PDF_FOCUS_REQUEST')requestFocus(msg.topic); if(msg.type==='PDF_FOCUS_RESULT'&&msg.requestId===focusRequestId){focusKeywords=null;focusPrefixes=msg.relevant||[];sendStatus('focus','success');render();} if(msg.type==='PDF_FOCUS_ERROR'&&msg.requestId===focusRequestId){focusPrefixes=null;sendStatus('focus','error');render();} if(msg.type==='AI_RETRY'){ if(msg.feature==='emotion'){emotionWords=[];emotionPending=null;requestEmotion();} if(msg.feature==='labels'){labelBySentence.clear();labelPending=null;requestLabels();} } }
const tabReady = chrome.tabs.getCurrent().then(tab=>{ownTabId=tab?.id??null; sendPdf('PDF_READER_STATUS', { active:true });});
chrome.storage.sync.get(['draSettings','draWordLists'],data=>{settings={...DEFAULTS,...data.draSettings};wordLists={...FALLBACK_WORDS,...data.draWordLists};typeInterval=typeSpeed(settings.typewriterSpeed);tabReady.then(loadPdf);});
chrome.storage.onChanged.addListener((changes,area)=>{if(area!=='sync')return; if(changes.draSettings){const wasTypewriter=settings.typewriterActive;settings={...DEFAULTS,...changes.draSettings.newValue};typeInterval=typeSpeed(settings.typewriterSpeed);if(settings.typewriterActive!==wasTypewriter)setTypewriter(settings.typewriterActive);else {emotionPending=null;labelPending=null;emotionWords=[];labelBySentence.clear();render();runAiIfNeeded();}} if(changes.draWordLists){wordLists={...FALLBACK_WORDS,...changes.draWordLists.newValue};render();}});
chrome.runtime.onMessage.addListener(handlePdfMessage);
document.querySelectorAll('.dra-reader-actions [data-theme]').forEach(btn=>btn.addEventListener('click',()=>{app.dataset.theme=btn.dataset.theme;document.querySelectorAll('.dra-reader-actions [data-theme]').forEach(b=>b.classList.toggle('active',b===btn));}));
article.addEventListener('click',event=>{if(!tw)return;if(event.target.closest('[data-tw-action="start-beginning"]')){chooseStart(0);return;}if(tw.phase==='picking-start'){const el=event.target.closest('[data-tw-index]');if(el)chooseStart(Number(el.dataset.twIndex));}});
addEventListener('keydown',event=>{if(event.key==='Escape')document.getElementById('close-reader').click();if(event.key===' '&&tw){event.preventDefault();advanceTypewriter();}}); scroll.addEventListener('scroll',updateProgress);addEventListener('mousemove',updateRuler);addEventListener('beforeunload',()=>chrome.runtime.sendMessage({type:'PDF_READER_STATUS',active:false,tabId:ownTabId}));
document.getElementById('close-reader').addEventListener('click',async()=>{chrome.runtime.sendMessage({type:'PDF_READER_STATUS',active:false,tabId:ownTabId});const tab=await chrome.tabs.getCurrent();if(tab?.id)chrome.tabs.remove(tab.id);});
