export const DEFAULT_SETTINGS = {
  panelSize:             'comfortable',
  typographyEnabled:     false,
  readingAidsEnabled:    false,
  boldBeginning:         false,
  emotionColor:          false,
  emotionMode:           'local', // 'ai' | 'local'
  gradientRows:          false,
  rowShadingColor:       '#bfb3d0',
  transitionAnimation:   false,
  sentenceLabels:        false,
  sentenceLabelsMode:    'local', // 'ai' | 'local'
  sentenceLabelsLens:    'news',  // 'news' | 'stem' | 'humanities' | 'fiction'
  labelCoreFactColor:    '#eab308',
  labelContextColor:     '#3b82f6',
  labelQuoteColor:       '#ea580c',
  labelConceptColor:     '#9333ea',
  labelMechanismColor:   '#f97316',
  labelConstraintColor:  '#ef4444',
  labelThesisColor:      '#ca8a04',
  labelEvidenceColor:    '#22c55e',
  labelExplanationColor: '#6b7280',
  labelDialogueColor:    '#ec4899',
  labelPlotTurnColor:    '#eab308',
  labelSettingColor:     '#9ca3af',
  topicFocusMode:        'local', // 'ai' | 'local'
  fontSize:             null,
  lineHeight:           null,
  fontFamily:           null,
  wordSpacing:          0,
  letterSpacing:        0,
  emotionPositiveColor: '#27ae60',
  emotionNegativeColor: '#e74c3c',
  emotionComplexColor:  '#8e44ad',
  rulerActive:          false,
  rulerWindowLines:     1.5,
  autoScrollActive:     false,
  autoScrollSpeed:      2,
  typewriterActive:     false,
  typewriterSpeed:      5,
};
